[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[nightly.build]
rustflags = ["-Z", "threads=8"]

[nightly.unstable]
codegen-backend = true

[nightly.profile.dev]
codegen-backend = "cranelift"